//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dander.Web.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JavaScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavaScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dander.Web.Net.JavaScripts", typeof(JavaScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dander.Web.Shop.DisplayedItem = /*constructor*/ function (/*jqeuryObject*/ _jqThis, /*string*/ _itemRef, /*string*/ _getContentURL)
        ///{
        ///    console.assert(_jqThis.length == 1, &apos;Argument is required represent a unique DOM element wrapped as a JQuery Object.&apos;);
        ///    Dander.Utility.assertNoneEmptyString(_itemRef);
        ///    Dander.Utility.assertNoneEmptyString(_getContentURL);
        ///
        ///    /*inheritance*/
        ///    Dander.Web.Shop.Abstract.DisplayedItem.call(this);
        ///
        ///    /*priviliged*/
        ///    this.ajaxRefresh = function ()
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dander_item_display_jquery3_1_1 {
            get {
                return ResourceManager.GetString("dander_item_display_jquery3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // defining up &quot;namespaces&quot;
        ///Dander =
        ///{
        ///	Utility: {},
        ///	Abstract: {},
        ///	Web:
        ///	{
        ///		Abstract: {},
        ///		Shop:
        ///        {
        ///            Abstract: {}
        ///        }
        ///	}
        ///};
        ///
        ///Dander.Utility.assertNoneEmptyString = function (/*any*/ arg)
        ///{
        ///	console.assert(typeof arg == &apos;string&apos; &amp;&amp; arg.length &gt; 0, &apos;Argument is required to be a none-empty string.&apos;);
        ///}
        ///Object.defineProperty(Dander.Utility, &apos;assertNoneEmptyString&apos;, { enumerable: false, writeable: false, configurable: false });
        ///
        ///Dander.Utility.assertInt1plus = fun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dander_web_net_1_0_0 {
            get {
                return ResourceManager.GetString("dander_web_net_1_0_0", resourceCulture);
            }
        }
    }
}
